### ISSUE TITLE
[Suggestion] Only run `rm` in the install script if `adduce` already exists in the fs

### ISSUE THREAD

**Issue by tulpenkiste** [DeclanChidlow/Adduce#22]
https://github.com/DeclanChidlow/Adduce/blob/aba32d1e2145fbb51f276036a26329c57ba27183/install.sh#L3

This causes a non-fatal error (the rest of the script continues as normal) which looks a bit weird on a first install but this can be avoided by checking if the file exists.
E.g.
```bash
if [[ -f /bin/adduce ]]; then
    sudo rm /bin/adduce
fi
```

**Comment by DeclanChidlow** [comment]
Thanks for the suggestion. Implemented with 3fc2bc073ba8c8ab0d9a8d5d9ccad7c0870b5224.
