### ISSUE TITLE
crates.io

### ISSUE THREAD

**Issue by toastxc** [DeclanChidlow/Adduce#26]
Hi Vale!
I've been moving all of my stuff to flathub & crates.io and I think it'd be good if the same was done for Adduce.

It'd made installation easier and more accessible and its not difficult to do.

**Comment by toastxc** [comment]
On a related note: I also made [this](https://github.com/DeclanChidlow/Adduce/tree/toastxc-install-patch).
Sorry for the spam, I was intending to do this for a while.

**Comment by toastxc** [comment]
Ideally, once we're done people will be able to install Adduce just by:
```bash
cargo install adduce
```

**Comment by DeclanChidlow** [comment]
I'm onboard with the easier installation and adoption into package managers and better formats.

However, I think we should move away from maintaining an installation BASH script due to bad system interoperability. I know that both the current and your proposed script fail on NixOS.

**Comment by DeclanChidlow** [comment]
Published on https://crates.io.

https://crates.io/crates/adduce
